### ISSUE TITLE
Infinite redirection loop

### ISSUE THREAD

**Issue by platix** [ONLYOFFICE/CommunityServer#10]
In Ubuntu on latest version of the repo, When I restart the server and try to connect to the web with non authenticated navigator, this do an infinite redirect loop to /auth.aspx

**Comment by AnaMih** [comment]
Sorry for any inconveniences. The issue has been detected, the fix will be included into the next version. Please follow the instructions in order to resolve it:
1) Edit the file /var/www/onlyoffice/WebStudio/web.appsettings.config
2) Find and delete the line <add key="web.warmup.type" value="basic" />
3) sudo service monoserve stop \ start

**Comment by platix** [comment]
the fix works well.
thanks
