### ISSUE TITLE
Add RTL features 

### ISSUE THREAD

**Issue by omoridi** [ONLYOFFICE/CommunityServer#371]
Hi, 
This office work only with ltr languages and why do not support rtl?

**Comment by ShockwaveNN** [comment]
Hi, if you got problem with RTL in ONLYOFFICE DocumentServer\DesktopEditors - this issue is duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/19

If you got problems with RTL in ONLYOFFICE CommunityServer (since you've posted bug in this repo) - please describe this problem in more details)
