### ISSUE TITLE
Code changes do not take effect

### ISSUE THREAD

**Issue by wanghx12** [ONLYOFFICE/CommunityServer#490]
hi，
I deployed office components using docker, Version: Community Server: latest 12.5.2

Recently I modified code of ./web/studio/ASC.Web.Studio/addons/calendar/UserControls/fullcalendar/fullcalendar.js  and web/studio/ASC.Web.Studio/UserControls/Common/Authorize/Authorize.ascx  files. 
Then I compiled the source code, follow this [instruction](https://helpcenter.onlyoffice.com/server/windows/community/compile-source-code.aspx). 
After compiling, I replaced  ASC.Web.Studio.dll and ASC.Web.Calendar.dll  files in location /var/www/onlyoffice/WebStudio/bin/ of container onlyoffice-community-server, but change does not take effect. But if I modified the cs files it works.

I noticed that in the csproj files, these two files will not be compiled, but directly referenced through the Content Include method,  How can I make this change take effect,  is there anything I can do?

Thanks in advance.

**Comment by Carazyda** [comment]
Hello @wanghx12 For fullcalendar.js you can make changes on the server. After that, delete `/var/www/onlyoffice/Data/bundle` and `systemctl restart monoserve`.

For Authorize.ascx, you should copy all WebStudio/bin files because we are using a pre-compilation method. And also `systemctl restart monoserve` after copying files.
